version: '3'
services:
  webviz:
    image: hdwlab/webviz:hdl-dev
    container_name: webviz
    ports:
      - 8080:8080
    volumes:
      - ${PWD}:/opt/webviz:cached
    working_dir: /opt/webviz
    entrypoint: ''
    command: bash
    tty: true
